# Generated by Django 5.2.6 on 2025-09-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
