# Generated by Django 5.2.6 on 2025-09-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_unlikes_to_packages'),
        ('payments', '0002_remove_purchase_stripe_payment_intent_id_and_more'),
    ]

    operations = [
    ]
