# Generated by Django 5.2.6 on 2025-10-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_merge_20250918_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='DislikePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unlikes', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='likepackage',
            name='unlikes',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='package',
        ),
        migrations.AddField(
            model_name='purchase',
            name='like_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='payments.likepackage'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='package_type',
            field=models.CharField(choices=[('like', 'Like Package'), ('dislike', 'Dislike Package')], default='like', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='dislike_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='payments.dislikepackage'),
        ),
    ]
