# Generated by Django 5.2.6 on 2025-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_dislikepackage_remove_likepackage_unlikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe')], default='paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
