# Generated by Django 5.2.6 on 2025-10-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_purchase_payment_provider_purchase_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='viva_order_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='viva_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('viva', 'Viva Wallet')], default='paystack', max_length=20),
        ),
    ]
