# Generated by Django 5.2.6 on 2025-10-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_purchase_viva_order_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('likes_count', models.IntegerField(help_text='Number of likes included in this package')),
                ('boosters', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='dislike_package',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='like_package',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='viva_order_code',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='viva_transaction_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='usage_type',
            field=models.CharField(choices=[('likes', 'For Giving Likes'), ('dislikes', 'For Giving Dislikes')], default='likes', help_text='Whether user will use these for likes or dislikes', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe')], default='paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='payments.package'),
        ),
        migrations.DeleteModel(
            name='DislikePackage',
        ),
    ]
