# Generated by Django 5.2.6 on 2025-10-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_purchase_package'),
        ('payments', '0007_package_remove_purchase_dislike_package_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePackage',
        ),
    ]
