# Generated by Django 5.2.6 on 2025-10-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_delete_likepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('GHS', 'Ghana Cedis (GH₵)')], default='EUR', max_length=3),
        ),
    ]
