# Generated by Django 5.2.6 on 2025-10-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_package_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='points_reward',
            field=models.IntegerField(default=0, help_text='Points awarded when this package is purchased'),
        ),
    ]
