# Generated by Django 5.2.6 on 2025-09-18 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_complete'], name='profiles_pr_is_comp_a5aa2d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['study_field'], name='profiles_pr_study_f_a93ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['location'], name='profiles_pr_locatio_8c34ab_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['birth_date'], name='profiles_pr_birth_d_eb165b_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_at'], name='profiles_pr_created_b275ca_idx'),
        ),
    ]
