# Generated by Django 5.2.6 on 2025-10-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_add_location_coordinates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profile',
            new_name='profiles_pr_school__9ccd39_idx',
            old_name='profiles_pr_school__idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profiles_pr_city_491350_idx',
            old_name='profiles_pr_city_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='General location/region', max_length=100),
        ),
    ]
