# Generated by Django 5.2.6 on 2025-10-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_profiles_pr_school__idx_profiles_pr_school__9ccd39_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
    ]
