# Generated by Django 5.2.6 on 2025-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
