# Generated by Django 5.2.6 on 2025-10-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('payments', '0007_package_remove_purchase_dislike_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_purchases', to='payments.package'),
        ),
    ]
