# Generated by Django 5.2.6 on 2025-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_unlikes_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='received_likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='received_super_likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='received_unlikes_count',
            field=models.IntegerField(default=0),
        ),
    ]
