# Generated by Django 5.2.6 on 2025-10-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='received_super_likes_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='super_likes_balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='unlikes_balance',
        ),
    ]
