# Generated by Django 5.2.6 on 2025-10-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_received_super_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='likes_balance',
            field=models.IntegerField(default=100),
        ),
    ]
