# Generated by Django 5.2.6 on 2025-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_likes_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='likes_spent_on_rewards',
            field=models.IntegerField(default=0),
        ),
    ]
