# Generated by Django 5.2.6 on 2025-09-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_add_unlike_model'),
        ('likes', '0002_remove_unique_constraint'),
    ]

    operations = [
    ]
