# Generated by Django 5.2.6 on 2025-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_merge_20250918_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='amount',
            field=models.PositiveIntegerField(default=1, help_text='Number of likes given'),
        ),
        migrations.AddField(
            model_name='unlike',
            name='amount',
            field=models.PositiveIntegerField(default=1, help_text='Number of unlikes given'),
        ),
    ]
