# Generated by Django 5.2.6 on 2025-10-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_like_amount_unlike_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_type',
        ),
    ]
