# Generated by Django 5.2.6 on 2025-11-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='likes_required',
            field=models.IntegerField(default=0, help_text='Number of likes required to claim this reward'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='points_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('physical', 'Physical Item'), ('digital', 'Digital Item'), ('discount', 'Discount Voucher'), ('experience', 'Experience'), ('money', 'Money Reward')], max_length=20),
        ),
    ]
