# Generated by Django 5.2.6 on 2025-11-10 18:22

from django.db import migrations


def create_money_rewards(apps, schema_editor):
    """Create the three money rewards based on likes"""
    Reward = apps.get_model('rewards', 'Reward')

    # Create the three money rewards
    rewards_data = [
        {
            'name': 'GHS 400',
            'description': 'Claim GHS 400 when you reach 10,000 likes! This is a one-time reward that can be claimed once you achieve this milestone.',
            'points_cost': 0,
            'reward_type': 'money',
            'stock_quantity': 0,  # Unlimited
            'likes_required': 10000,
            'is_active': True,
        },
        {
            'name': 'GHS 790',
            'description': 'Claim GHS 790 when you reach 22,000 likes! This is a one-time reward that can be claimed once you achieve this milestone.',
            'points_cost': 0,
            'reward_type': 'money',
            'stock_quantity': 0,  # Unlimited
            'likes_required': 22000,
            'is_active': True,
        },
        {
            'name': 'GHS 1170',
            'description': 'Claim GHS 1170 when you reach 32,000 likes! This is a one-time reward that can be claimed once you achieve this milestone.',
            'points_cost': 0,
            'reward_type': 'money',
            'stock_quantity': 0,  # Unlimited
            'likes_required': 32000,
            'is_active': True,
        },
    ]

    for reward_data in rewards_data:
        Reward.objects.create(**reward_data)


def remove_money_rewards(apps, schema_editor):
    """Remove the money rewards if we need to reverse the migration"""
    Reward = apps.get_model('rewards', 'Reward')
    Reward.objects.filter(
        reward_type='money',
        name__in=['GHS 400', 'GHS 790', 'GHS 1170']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_reward_likes_required_alter_reward_points_cost_and_more'),
    ]

    operations = [
        migrations.RunPython(create_money_rewards, remove_money_rewards),
    ]
