# Generated by Django 5.2.6 on 2025-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_add_money_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Prize title (e.g., '1st Prize - $5,000 Cash!')", max_length=200)),
                ('description', models.TextField(help_text='Prize description')),
                ('prize_value', models.CharField(help_text="Prize value display (e.g., '$5,000' or 'GHS 9,000')", max_length=100)),
                ('position', models.CharField(choices=[('1st', '1st Prize'), ('2nd', '2nd Prize'), ('3rd', '3rd Prize')], max_length=10, unique=True)),
                ('icon', models.CharField(default='fa-trophy', help_text="FontAwesome icon class (e.g., 'fa-trophy', 'fa-plane')", max_length=50)),
                ('background_color', models.CharField(default='#FFD700', help_text='Hex color code for background', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Show this prize in the banner')),
                ('display_order', models.IntegerField(default=0, help_text='Order in the slider (lower numbers first)')),
                ('start_date', models.DateTimeField(blank=True, help_text='When to start showing this banner', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing this banner', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prize Announcement',
                'verbose_name_plural': 'Prize Announcements',
                'ordering': ['display_order', 'position'],
            },
        ),
    ]
