# Generated by Django 5.2.6 on 2025-11-10 19:00

from django.db import migrations
from datetime import datetime


def create_grand_prizes(apps, schema_editor):
    """Create the three end-of-year grand prizes"""
    PrizeAnnouncement = apps.get_model('rewards', 'PrizeAnnouncement')

    # Define the three grand prizes
    prizes_data = [
        {
            'position': '1st',
            'title': '🏆 1st Prize - $5,000 Cash!',
            'description': 'Grand prize winner receives $5,000 cash! Be active, get likes, and you could be our lucky winner!',
            'prize_value': '$5,000',
            'icon': 'fa-trophy',
            'background_color': '#FFD700',  # Gold
            'is_active': True,
            'display_order': 1,
        },
        {
            'position': '2nd',
            'title': '✈️ 2nd Prize - Dream Holiday Trip!',
            'description': 'Win an amazing holiday trip worth $2,000! Explore the world on us!',
            'prize_value': '$2,000 Holiday',
            'icon': 'fa-plane',
            'background_color': '#C0C0C0',  # Silver
            'is_active': True,
            'display_order': 2,
        },
        {
            'position': '3rd',
            'title': '💰 3rd Prize - GHS 9,000 Cash!',
            'description': 'Third place winner takes home GHS 9,000! Stay engaged and keep posting!',
            'prize_value': 'GHS 9,000',
            'icon': 'fa-money-bill-wave',
            'background_color': '#CD7F32',  # Bronze
            'is_active': True,
            'display_order': 3,
        },
    ]

    for prize_data in prizes_data:
        PrizeAnnouncement.objects.create(**prize_data)


def remove_grand_prizes(apps, schema_editor):
    """Remove the grand prizes if migration is reversed"""
    PrizeAnnouncement = apps.get_model('rewards', 'PrizeAnnouncement')
    PrizeAnnouncement.objects.filter(
        position__in=['1st', '2nd', '3rd']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_prizeannouncement'),
    ]

    operations = [
        migrations.RunPython(create_grand_prizes, remove_grand_prizes),
    ]
