# Generated by Django 5.2.6 on 2025-10-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['-display_priority', '-created_at'], name='advertiseme_display_45f0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['is_active', '-display_priority'], name='advertiseme_is_acti_53449c_idx'),
        ),
    ]
