# Generated by Django 5.2.6 on 2025-10-26 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_advertiseme_display_45f0c3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.CharField(blank=True, help_text='Short description to display with the ad', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='brand_url',
            field=models.URLField(blank=True, help_text='Website URL (optional)', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
