"""
Django settings for mooibanana_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ["mooibanana-project-1.onrender.com","*","mooibanana.site"]
#config('ALLOWED_HOSTS', default='').split(',')

CSRF_TRUSTED_ORIGINS = [
    'https://mooibanana-project-295618807617.europe-west1.run.app',
    'https://mooibanana-project-*.run.app',  # Allow any revision
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    "https://mooibanana-project-1.onrender.com",
    "https://draggy-unprecipitately-harper.ngrok-free.dev",
    "https://www.mooibanana.site",
    "https://mooibanana.digitalrepublic.space"
]

# CSRF Settings
CSRF_COOKIE_SECURE = not DEBUG  # Only require HTTPS in production
CSRF_COOKIE_HTTPONLY = False    # Allow JavaScript to access CSRF cookie for AJAX requests
CSRF_USE_SESSIONS = False       # Use cookie-based CSRF tokens
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',  # Must be before staticfiles
    'django.contrib.staticfiles',
    'cloudinary',  # Cloudinary
    'channels',  # WebSocket support
    'crispy_forms',
    'crispy_bootstrap5',

    # Custom apps
    'accounts',
    'profiles',
    'likes',
    'rewards',
    'chat',
    'payments',
    'notifications',
    'admin_dashboard',
    'updates',
    'advertisements',
    'quiz',
    'social',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Performance settings
if not DEBUG:
    # Enable GZip compression
    MIDDLEWARE.insert(1, 'django.middleware.gzip.GZipMiddleware')

    # Enable conditional GET middleware
    MIDDLEWARE.append('django.middleware.http.ConditionalGetMiddleware')

ROOT_URLCONF = 'mooibanana_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rewards.context_processors.prize_announcements',
            ],
        },
    },
]

WSGI_APPLICATION = 'mooibanana_project.wsgi.application'
ASGI_APPLICATION = 'mooibanana_project.asgi.application'

# Channel layers for WebSocket support
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# Database configuration
DATABASE_URL = config('DATABASE_URL')
DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL)
}

# Caching
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Session optimization
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# Database connection pooling and optimization
CONN_MAX_AGE = 60  # Keep database connections alive for 60 seconds

# File upload optimization
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Static files optimization
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Performance monitoring (only in DEBUG mode)
# if DEBUG:
#     INSTALLED_APPS += ['debug_toolbar']
#     MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
#     INTERNAL_IPS = ['127.0.0.1']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


 #Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Login/Logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'profiles:discover'
LOGOUT_REDIRECT_URL = 'home'

# Email settings
# Use console backend for development/testing (emails will appear in terminal)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SMTP settings for production (enable when Gmail app password is ready)
# Try SSL configuration first as it's more reliable with Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'kennedyakogokweku@gmail.com'
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Replace with actual app password
DEFAULT_FROM_EMAIL = 'kennedyakogokweku@gmail.com'
EMAIL_TIMEOUT = 60

# Alternative TLS configuration (if SSL doesn't work)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST_USER = 'kennedyakogokweku@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-16-character-app-password'  # Replace with actual app password
# DEFAULT_FROM_EMAIL = 'kennedyakogokweku@gmail.com'
# EMAIL_TIMEOUT = 60

# Paystack settings (for Ghana)
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')

# Stripe settings (for Europe - deprecated, replaced by Viva Wallet)
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')

# Viva Wallet settings (for European users)
VIVA_MERCHANT_ID = config('VIVA_MERCHANT_ID', default='')
VIVA_API_KEY = config('VIVA_API_KEY', default='')
VIVA_CLIENT_ID = config('VIVA_CLIENT_ID', default='')
VIVA_CLIENT_SECRET = config('VIVA_CLIENT_SECRET', default='')
VIVA_SOURCE_CODE = config('VIVA_SOURCE_CODE', default='')
VIVA_ENVIRONMENT = config('VIVA_ENVIRONMENT', default='demo')  # 'demo' or 'production'

# Custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_API_KEY'),
    'API_SECRET': config('CLOUDINARY_API_SECRET'),
}

# Advertisement feature flags (can be controlled via environment)
# Set these in your environment or .env file to enable specific placements
SHOW_IN_FEED_AD = config('SHOW_IN_FEED_AD', default=False, cast=bool)
SHOW_IN_GRID_AD = config('SHOW_IN_GRID_AD', default=False, cast=bool)
SHOW_PROFILE_BANNER_AD = config('SHOW_PROFILE_BANNER_AD', default=False, cast=bool)
SHOW_POST_BANNER_AD = config('SHOW_POST_BANNER_AD', default=False, cast=bool)

# Use Cloudinary for media files (Django 4.2+ uses STORAGES)
STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Fallback for older Django versions
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# AWS CloudWatch Configuration (Optional)
AWS_CLOUDWATCH_ENABLED = config('AWS_CLOUDWATCH_ENABLED', default=False, cast=bool)
AWS_REGION_NAME = config('AWS_REGION_NAME', default='us-east-1')
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
CLOUDWATCH_LOG_GROUP = config('CLOUDWATCH_LOG_GROUP', default='mooibanana-app')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {name} {module} {funcName} {lineno:d} {message}',
            'style': '{',
        },
        'cloudwatch': {
            'format': '{levelname} {name} {module} {funcName} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'app.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose'
        },
        'payments_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'payments.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'detailed'
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'detailed'
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'detailed'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'payments': {
            'handlers': ['console', 'payments_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'likes': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'rewards': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'notifications': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'chat': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'profiles': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    }
}

# Conditionally add CloudWatch handlers if enabled
if AWS_CLOUDWATCH_ENABLED and AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    try:
        import boto3
        import watchtower

        # Create CloudWatch handlers
        cloudwatch_handler_config = {
            'level': 'INFO',
            'class': 'watchtower.CloudWatchLogHandler',
            'boto3_client': boto3.client(
                'logs',
                region_name=AWS_REGION_NAME,
                aws_access_key_id=AWS_ACCESS_KEY_ID,
                aws_secret_access_key=AWS_SECRET_ACCESS_KEY
            ),
            'log_group_name': CLOUDWATCH_LOG_GROUP,
            'formatter': 'cloudwatch',
        }

        # Add CloudWatch handlers for different log streams
        LOGGING['handlers']['cloudwatch_general'] = {
            **cloudwatch_handler_config,
            'log_stream_name': 'general-{strftime:%Y-%m-%d}',
        }

        LOGGING['handlers']['cloudwatch_payments'] = {
            **cloudwatch_handler_config,
            'level': 'DEBUG',
            'log_stream_name': 'payments-{strftime:%Y-%m-%d}',
        }

        LOGGING['handlers']['cloudwatch_errors'] = {
            **cloudwatch_handler_config,
            'level': 'ERROR',
            'log_stream_name': 'errors-{strftime:%Y-%m-%d}',
        }

        LOGGING['handlers']['cloudwatch_security'] = {
            **cloudwatch_handler_config,
            'level': 'WARNING',
            'log_stream_name': 'security-{strftime:%Y-%m-%d}',
        }

        # Add CloudWatch handlers to existing loggers
        LOGGING['loggers']['django']['handlers'].append('cloudwatch_general')
        LOGGING['loggers']['django.request']['handlers'].append('cloudwatch_errors')
        LOGGING['loggers']['django.security']['handlers'].append('cloudwatch_security')
        LOGGING['loggers']['payments']['handlers'].append('cloudwatch_payments')
        LOGGING['loggers']['payments']['handlers'].append('cloudwatch_errors')
        LOGGING['loggers']['accounts']['handlers'].append('cloudwatch_general')
        LOGGING['loggers']['likes']['handlers'].append('cloudwatch_general')
        LOGGING['loggers']['rewards']['handlers'].append('cloudwatch_general')
        LOGGING['loggers']['notifications']['handlers'].append('cloudwatch_general')
        LOGGING['loggers']['security']['handlers'].append('cloudwatch_security')

        print(f"✓ CloudWatch logging enabled - Log Group: {CLOUDWATCH_LOG_GROUP}, Region: {AWS_REGION_NAME}")
    except ImportError:
        print("⚠ CloudWatch logging enabled but watchtower/boto3 not installed. Run: pip install watchtower boto3")
    except Exception as e:
        print(f"⚠ CloudWatch logging configuration failed: {str(e)}")
else:
    if AWS_CLOUDWATCH_ENABLED:
        print("⚠ CloudWatch enabled but AWS credentials not configured")