"""
Django settings for mooibanana_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ["mooibanana-project-1.onrender.com","*","mooibanana.site"]
#config('ALLOWED_HOSTS', default='').split(',')

CSRF_TRUSTED_ORIGINS = [
    'https://mooibanana-project-295618807617.europe-west1.run.app',
    'https://mooibanana-project-*.run.app',  # Allow any revision
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    "https://mooibanana-project-1.onrender.com",
    "https://draggy-unprecipitately-harper.ngrok-free.dev",
    "https://www.mooibanana.site"
    "https://mooibanana.digitalrepublic.space"
    
    
]

# CSRF Settings
CSRF_COOKIE_SECURE = not DEBUG  # Only require HTTPS in production
CSRF_COOKIE_HTTPONLY = False    # Allow JavaScript to access CSRF cookie for AJAX requests
CSRF_USE_SESSIONS = False       # Use cookie-based CSRF tokens
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',  # Must be before staticfiles
    'django.contrib.staticfiles',
    'cloudinary',  # Cloudinary
    'channels',  # WebSocket support
    'crispy_forms',
    'crispy_bootstrap5',

    # Custom apps
    'accounts',
    'profiles',
    'likes',
    'rewards',
    'chat',
    'payments',
    'notifications',
    'admin_dashboard',
    'updates',
    'advertisements',
    'quiz',
    'social',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Performance settings
if not DEBUG:
    # Enable GZip compression
    MIDDLEWARE.insert(1, 'django.middleware.gzip.GZipMiddleware')

    # Enable conditional GET middleware
    MIDDLEWARE.append('django.middleware.http.ConditionalGetMiddleware')

ROOT_URLCONF = 'mooibanana_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rewards.context_processors.prize_announcements',
            ],
        },
    },
]

WSGI_APPLICATION = 'mooibanana_project.wsgi.application'
ASGI_APPLICATION = 'mooibanana_project.asgi.application'

# Channel layers for WebSocket support
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# Database configuration
DATABASE_URL = config('DATABASE_URL')
DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL)
}

# Caching
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Session optimization
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# Database connection pooling and optimization
CONN_MAX_AGE = 60  # Keep database connections alive for 60 seconds

# File upload optimization
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Static files optimization
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Performance monitoring (only in DEBUG mode)
# if DEBUG:
#     INSTALLED_APPS += ['debug_toolbar']
#     MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
#     INTERNAL_IPS = ['127.0.0.1']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


 #Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Login/Logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'profiles:discover'
LOGOUT_REDIRECT_URL = 'home'

# Email settings
# Use console backend for development/testing (emails will appear in terminal)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SMTP settings for production (enable when Gmail app password is ready)
# Try SSL configuration first as it's more reliable with Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'kennedyakogokweku@gmail.com'
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Replace with actual app password
DEFAULT_FROM_EMAIL = 'kennedyakogokweku@gmail.com'
EMAIL_TIMEOUT = 60

# Alternative TLS configuration (if SSL doesn't work)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST_USER = 'kennedyakogokweku@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-16-character-app-password'  # Replace with actual app password
# DEFAULT_FROM_EMAIL = 'kennedyakogokweku@gmail.com'
# EMAIL_TIMEOUT = 60

# Paystack settings (for Ghana)
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')

# Stripe settings (for Europe - deprecated, replaced by Viva Wallet)
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')

# Viva Wallet settings (for European users)
VIVA_MERCHANT_ID = config('VIVA_MERCHANT_ID', default='')
VIVA_API_KEY = config('VIVA_API_KEY', default='')
VIVA_CLIENT_ID = config('VIVA_CLIENT_ID', default='')
VIVA_CLIENT_SECRET = config('VIVA_CLIENT_SECRET', default='')
VIVA_SOURCE_CODE = config('VIVA_SOURCE_CODE', default='')
VIVA_ENVIRONMENT = config('VIVA_ENVIRONMENT', default='demo')  # 'demo' or 'production'

# Custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_API_KEY'),
    'API_SECRET': config('CLOUDINARY_API_SECRET'),
}

# Advertisement feature flags (can be controlled via environment)
# Set these in your environment or .env file to enable specific placements
SHOW_IN_FEED_AD = config('SHOW_IN_FEED_AD', default=False, cast=bool)
SHOW_IN_GRID_AD = config('SHOW_IN_GRID_AD', default=False, cast=bool)
SHOW_PROFILE_BANNER_AD = config('SHOW_PROFILE_BANNER_AD', default=False, cast=bool)
SHOW_POST_BANNER_AD = config('SHOW_POST_BANNER_AD', default=False, cast=bool)

# Use Cloudinary for media files (Django 4.2+ uses STORAGES)
STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Fallback for older Django versions
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'