# Generated by Django 5.2.6 on 2025-09-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('match_request', 'Match Request'), ('match_accepted', 'Match Accepted'), ('match_declined', 'Match Declined'), ('new_message', 'New Message'), ('gift_received', 'Gift Received'), ('like_received', 'Like Received'), ('unlike_received', 'Unlike Received')], max_length=20),
        ),
    ]
